// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvdvigdekckwokeeochn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZHZpZ2Rla2Nrd29rZWVvY2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDEyNzEsImV4cCI6MjA2MzUxNzI3MX0.zSi2dh3E3ZuS_VYOZvYYYgTtdLZ249J7M3u0z0Sk6-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);